version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=cdn
  
  redis:
    image: redis:6.2
    restart: always

  cdn:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "/app/main migrate_up | true; /app/main runserver --host 0.0.0.0"
    ports:
      - "5000:5000"
    environment:
      - DB_URI=postgres://root:secret@postgres:5432/cdn?sslmode=disable
      - SECRET_KEY=mysecret # make sure to keep the same secret key in the jwt issuer
      - MAX_FILE_SIZE=30
      - REDIS_HOST=redis:6379
      - REDIS_DB=0
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
  
